### ISSUE TITLE
Computer Player algorithm for making a move

### ISSUE THREAD

**Issue by ethanhonest** [CSC207-2022F-UofT/course-project-scramblers#15]
Goes through dictionary and existing letters to find a word to place

**Comment by petesaiacct** [comment]
Integrates a space search which verifies squares are available for letter placement. 
Creates an iterative search through available placements for words starting from smallest available placement to set boundary of available max space (8 tiles).
Chooses best word according to difficulty (easy = short, medium= medium, hard = longest)
Places word on board. removes tiles from AI bag,
Calculates word value adds to AI score. Checks win state
Replaces AI tiles.

**Comment by JosephSun2003** [comment]
Issues has been removed due to time contraints.
